In [11]:
import numpy as np
from utils import *

In [6]:
a = [
    [
        [
            -17,
            -29,
            -42
        ],
        [
            15,
            69,
            -60
        ],
        [
            73,
            15,
            -77
        ]
    ],
    [
        [
            56,
            -3,
            -19
        ],
        [
            -8,
            27,
            -105
        ],
        [
            24,
            -34,
            -115
        ]
    ],
    [
        [
            46,
            70,
            -60
        ],
        [
            -51,
            -12,
            -127
        ],
        [
            -26,
            26,
            -124
        ]
    ]
]

b = [
    [
        [0x62, 0x46, 0x3a], [0x60, 0x46, 0x39], [0x59, 0x3f, 0x32]
    ],
    [
        [0x58, 0x3d, 0x32], [0x55, 0x3e, 0x30], [0x4f, 0x37, 0x2b]
    ],
    [
        [0x48, 0x32, 0x27], [0x46, 0x33, 0x25], [0x41, 0x2d, 0x22]
    ]
]

a = np.asarray(a)
b = np.asarray(b)

In [7]:
print(a.shape)
print(b.shape)

(3, 3, 3)
(3, 3, 3)


In [8]:
s = 0
for c in range(3):
    for x in range(3):
        for y in range(3):
            s += a[c][x][y] * b[c][x][y]

s += 46314

print(s)

32309


In [9]:
print(a)

[[[ -17  -29  -42]
  [  15   69  -60]
  [  73   15  -77]]

 [[  56   -3  -19]
  [  -8   27 -105]
  [  24  -34 -115]]

 [[  46   70  -60]
  [ -51  -12 -127]
  [ -26   26 -124]]]


In [10]:
s * 32288 >> 25

31

In [18]:
l = []
for c in range(3):
    for x in range(3):
        for y in range(3):
            l.append(a[c][x][y] * b[c][x][y])
            print(dec2INT32InHex(a[c][x][y] * b[c][x][y]))

l.reverse()
l.append(46314)

80000682
800007ee
80000984
000005a0
000012de
80000d5c
00001961
000003b1
80000f0a
00001340
800000b7
800003b6
800002a8
0000068a
800013b0
00000768
8000074e
80001351
00000cf0
00000dac
80000924
80000df2
80000264
8000125b
8000069a
00000492
80001078


In [20]:
l1 = []
for i in range(len(l)):
    if i % 2 == 0:
        l1.append(l[i] + l[i + 1])
        print(dec2INT32InHex(l[i] + l[i + 1]))

80000be6
800018f5
80001056
00000488
80000661
0000001a
80000d26
8000065e
00001289
80000b59
00000c05
0000187e
80001172
0000ae68


In [22]:
l2 = []
for i in range(len(l1)):
    if i % 2 == 0:
        l2.append(l1[i] + l1[i + 1])
        print(dec2INT32InHex(l1[i] + l1[i + 1]))

800024db
80000bce
80000647
80001384
00000730
00002483
00009cf6


In [27]:
l3 = []
for i in range(len(l2) - 1):
    if i % 2 == 0:
        l3.append(l2[i] + l2[i + 1])
        print(dec2INT32InHex(l2[i] + l2[i + 1]))
l3.append(l2[6])

800030a9
800019cb
00002bb3


In [30]:
l4 = []
for i in range(len(l3)):
    if i % 2 == 0:
        l4.append(l3[i] + l3[i + 1])
        print(dec2INT32InHex(l3[i] + l3[i + 1]))

80004a74
0000c8a9


In [31]:
print(dec2INT32InHex(l4[0] + l4[1]))

00007e35


In [1]:
import re
fp = open("D:\\vivado_projects\\ip_repo\\MobileNet_1_0\\hdl\\tb\\pw_M_AXIS_TDATA.txt", 'r')
coe = open("D:\\vivado_projects\\ip_repo\\MobileNet_1_0\\hdl\\hex\\pw_conv_result.coe", 'w')

l = fp.readlines()
t = []
s = ""
for i in l:
    s = i[:-1] + s
sl = re.findall(r'.{64}', s)
sl.reverse()
# print(sl)

for t in sl:
    coe.write(t + ',\n')

fp.close()
coe.close()

In [1]:
"""
memory_initialization_radix=16;
memory_initialization_vector=
"""
import re
fp = open("D:\\vivado_projects\\ip_repo\\MobileNet_1_0\\hdl\\tb\\dw_cal_result.txt", 'r')
coe = open("D:\\vivado_projects\\ip_repo\\MobileNet_1_0\\hdl\\hex\\dw_cal_result.coe", 'w')

l = fp.readlines()
t = []
s = ""

for i in l:
    r = re.findall(r'.{8}', i)
    r.reverse()
    t += r

for i in t:
    coe.write(i + ', \n')

fp.close()
coe.close()

In [28]:
from utils import *
# w = [54,   62,   10,   34,   -4,   18,   31,   38,   40,   -18,   17,   14,   -63,   93,   -19,   -70,   7,   16,   -2,   35,   62,   0,   127,   -16,   -2,   -47,   23,   70,   36,   -34,   13,   11,   14,   36,   -15,   32,   41,   -33,   -18,   24,   -2,   11,   -28,   -81,   -2,   19,   -20,   30,   -12,   -8,   -13,   11,   -11,   21,   -21,   -40,   -62,   7,   28,   -33,   -20,   -56,   72,   7]
# w = [-34,-49,-30,79,27,-16,95,-34,84,63,21,-36,-11,-127,-24,-18,-63,-92,108,5,-79,30,-122,43,79,29,16,-92,-1,1,1,-61,52,-105,58,65,-70,0,-16,21,-102,-92,33,39,96,-24,21,-55,-1,-11,112,23,51,-55,-37,-94,-31,60,-116,24,20,41,57,36]
w = [11, -50, -33, 79, 104, 45, -35, 5, 50, 9, -84, 21, 33, -74, -47, -6, -19, 40, 19, 16, -83, -67, 64, 41, -35, -29, -76, -90, 73, 42, 58, -4, 11, 25, 0, 28, 30, -92, -59, 7, -27, 3, -127, -61, -28, -36, 7, -33, -35, -1, -8, -24, -91, -12, -17, -55, 50, 23, -67, -9, 90, 61, -1, 63]
b =  2754
M = 0x1b18d
# print(dec2INT32InHex(M))
import numpy as np
s1 = "080500000d0e00030300000f01000c0000000f1300000000000000121e00001b"
s2 = "04000043000000060a000000000000050200000000000614080f000000000000"
x = [0x08, 0x05, 0x00, 0x00, 0x0d, 0x0e, 0x00, 0x03, 0x03, 0x00, 0x00, 0x0f, 0x01, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x0f, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12, 0x1e, 0x00, 0x00, 0x1b, 0x04, 0x00, 0x00, 0x43, 0x00, 0x00, 0x00, 0x06, 0x0a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x14, 0x08, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
# import re
# r = re.findall(r'.{2}', s1)
# r += re.findall(r'.{2}', s2)
# r = np.asarray(r)
# for i in r:
#     print('0x' + i + ', ', end='')
# print(r.shape)
w.reverse()
sum = 0
for xt in range(32):
    sum += x[xt] * w[32 + xt]

sum1 = 0
for xt in range(32):
    sum1 += x[32 + xt] * w[xt]

print(dec2INT32InHex(sum))
print(dec2INT32InHex(sum1))
print(dec2INT32InHex(sum + sum1))

sum2 = sum + sum1 + b
print(dec2INT32InHex(sum2))

res = sum2 * M
print(dec2INT32InHex(res))

print(dec2INT32InHex((res >> 25)))

00000545
00001158
0000169d
0000215f
38841053
0000001c


In [35]:
r = re.findall(r'.{2}', '1104000b00000001001e2611050515000000000900080000000001141e001704')
for i in r:
    print(i, end=" ")

11 04 00 0b 00 00 00 01 00 1e 26 11 05 05 15 00 00 00 00 09 00 08 00 00 00 00 01 14 1e 00 17 04 

In [3]:
x = 0.046231940388679504
a = 0.010589840821921825
w = 1.0 / 49.0

m = x * w / a

from utils import *
t = InterFrExp(m)
print(t[0], t[1])

1530651995 -3


In [9]:
t = \
280+\
32 * 9 / 4 + 32 + 32 +\
640+\
64 * 9 / 4 + 64 + 64 +\
64 * 128 / 4 + 128 + 128+\
128 * 9 / 4 + 128 + 128 +\
128 * 128 / 4 + 128 + 128 +\
128 * 9 / 4 + 128 + 128+\
128 * 256 / 4 + 256 + 256 +\
256 * 9 / 4 + 256 + 256 +\
256 * 256 / 4 + 256 + 256 +\
256 * 9 / 4 + 256 + 256 +\
256 * 512 / 4 + 512 + 512 +\
512 * 9 / 4 + 512 + 512 +\
512 * 512 / 4 + 512 + 512 +\
512 * 9 / 4 + 512 + 512 +\
512 * 512 / 4 + 512 + 512 +\
512 * 9 / 4 + 512 + 512 +\
512 * 512 / 4 + 512 + 512 +\
512 * 9 / 4 + 512 + 512 +\
512 * 512 / 4 + 512 + 512 +\
512 * 9 / 4 + 512 + 512+\
512 * 512 / 4 + 512 + 512 +\
512 * 9 / 4 + 512 + 512 +\
512 * 1024 / 4 + 1024 + 1024 +\
1024 * 9 / 4 + 1024 + 1024+\
1024 * 1024 / 4 + 1024 + 1024 +\
64 * 1024 / 4 + 64 + 64


print(int(t))

834672


In [ ]:
for i in range(0, 26, 2):
    print('__init_array(%s, dw_conv_%d_quant, param_addr);' % (t[i], i / 2))
    print('param_addr += %s;' % (t[i]))
    print('__init_array(%s, pw_conv_%d_quant, param_addr);' % (t[i + 1], i / 2))
    print('param_addr += %s;' % (t[i + 1]))

In [22]:
import os
import cv2
import numpy as np
from PIL import Image

path = "C:\\Users\\38328\\Desktop\\pdf\\111\\"
save_path = "C:\\Users\\38328\\Desktop\\pdf\\111\\save\\"

d = os.walk(path)

l = []

for i in d:
    l.append(i)
print(l)

l = l[0][2]

print(len(l))
i = 0
for f in l:
    img = Image.open(path + f)
    # print(img)
    np_image = np.asarray(img)
    grayImage = cv2.cvtColor(np_image, cv2.COLOR_RGB2GRAY)
    cv2.imwrite(save_path + str(i) + '.jpg', grayImage)
    i += 1



[('C:\\Users\\38328\\Desktop\\pdf\\111\\', ['save'], ['RGB转YCbCr色彩空间波形图.png', 'top和down.png', 'YCbCr转RGB色彩空间波形图.png', '列驱动仿真波形.png', '列驱动的信号仿真波形图.png', '寄存器配置波形图.png', '对数转换仿真波形图.png', '指数转换放仿真波形图.png', '行扫描驱动仿真结果图.png', '行驱动仿真波形.png', '行驱动仿真波形图.png']), ('C:\\Users\\38328\\Desktop\\pdf\\111\\save', [], [])]
11
